# Site settings
title: "SCOWLv2"
email: "kevina@gnu.org"
description: ""
baseurl: ""
url: "https://en-wl.github.io"

# Build settings
#markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: pretty
